<?php

namespace Database\Seeders;

use App\Services\KindService;
use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder
{

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        KindService::Seeder('شهر', 'city', 'نام شهر', '', [
            ['key' => 'city-azarshahr', 'value_1' => 'آذرشهر', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-osko', 'value_1' => 'اسکو', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-ahar', 'value_1' => 'اهر', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-bostanabad', 'value_1' => 'بستان‌آباد', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-bonab', 'value_1' => 'بناب', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-tabriz', 'value_1' => 'تبریز', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-sorab', 'value_1' => 'سراب', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-shabster', 'value_1' => 'شبستر', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-jolfa', 'value_1' => 'جلفا', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-charavigagh', 'value_1' => 'چاراویماق', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-khodafarin', 'value_1' => 'خداآفرین', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-ajibshar', 'value_1' => 'عجب‌شیر', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-clibr', 'value_1' => 'کلیبر', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-maragheh', 'value_1' => 'مراغه', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-marand', 'value_1' => 'مرند', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-melkan', 'value_1' => 'ملکان', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-myaneh', 'value_1' => 'میانه', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-verzghan', 'value_1' => 'ورزقان', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-hashtrood', 'value_1' => 'هشترود', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-haris', 'value_1' => 'هریس', 'parent_key' => 'province-azarbayejan-sharghi'],
            ['key' => 'city-ashnaveeh', 'value_1' => 'اشنویه', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-ooromieh', 'value_1' => 'ارومیه', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-bookan', 'value_1' => 'بوکان', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-paldasht', 'value_1' => 'پلدشت', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-piranshahr', 'value_1' => 'پیرانشهر', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-tokab', 'value_1' => 'تکاب', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-salmas', 'value_1' => 'سلماس', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-sardasht', 'value_1' => 'سردشت', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-shahindezh', 'value_1' => 'شاهین‌دژ', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-shoot', 'value_1' => 'شوط', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-chaldoran', 'value_1' => 'چالدران', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-chaypareh', 'value_1' => 'چایپاره', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-khoy', 'value_1' => 'خوی', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-mako', 'value_1' => 'ماکو', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-mahabad', 'value_1' => 'مهاباد', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-miandoaab', 'value_1' => 'میاندوآب', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-naghde', 'value_1' => 'نقده', 'parent_key' => 'province-azarbayejan-gharbi'],
            ['key' => 'city-ardebil', 'value_1' => 'اردبیل', 'parent_key' => 'province-ardebil'],
            ['key' => 'city-eslandooz', 'value_1' => 'اصلاندوز', 'parent_key' => 'province-ardebil'],
            ['key' => 'city-bilehsavar', 'value_1' => 'بیله‌سوار', 'parent_key' => 'province-ardebil'],
            ['key' => 'city-parsabad', 'value_1' => 'پارس‌آباد', 'parent_key' => 'province-ardebil'],
            ['key' => 'city-khalkhal', 'value_1' => 'خلخال', 'parent_key' => 'province-ardebil'],
            ['key' => 'city-sarein', 'value_1' => 'سرعین', 'parent_key' => 'province-ardebil'],
            ['key' => 'city-kosar', 'value_1' => 'کوثر', 'parent_key' => 'province-ardebil'],
            ['key' => 'city-garmi', 'value_1' => 'گرمی', 'parent_key' => 'province-ardebil'],
            ['key' => 'city-meshginshahr', 'value_1' => 'مشگین‌شهر', 'parent_key' => 'province-ardebil'],
            ['key' => 'city-namin', 'value_1' => 'نمین', 'parent_key' => 'province-ardebil'],
            ['key' => 'city-nir', 'value_1' => 'نیر', 'parent_key' => 'province-ardebil'],
            ['key' => 'city-aran-bidgel', 'value_1' => 'آران و بیدگل', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-ardestan', 'value_1' => 'اردستان', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-esfehan', 'value_1' => 'اصفهان', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-barkhar', 'value_1' => 'برخوار', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-boein-meiandasht', 'value_1' => 'بوئین و میاندشت', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-tiran-kron', 'value_1' => 'تیران و کرون', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-chadgan', 'value_1' => 'چادگان', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-khomeinshahr', 'value_1' => 'خمینی‌شهر', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-khansar', 'value_1' => 'خوانسار', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-khor-biabanak', 'value_1' => 'خور و بیابانک', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-nehghan', 'value_1' => 'دهاقان', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-smiram', 'value_1' => 'سمیرم', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-shahinshar-mimeh', 'value_1' => 'شاهین‌شهر و میمه', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-shahreza', 'value_1' => 'شهرضا', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-flaorjan', 'value_1' => 'فلاورجان', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-fridan', 'value_1' => 'فریدن', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-freidonshahr', 'value_1' => 'فریدون‌شهر', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-khashan', 'value_1' => 'کاشان', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-golbayegan', 'value_1' => 'گلپایگان', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-lanjan', 'value_1' => 'لنجان', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-mobarakeh', 'value_1' => 'مبارکه', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-naein', 'value_1' => 'نائین', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-najafabad', 'value_1' => 'نجف‌آباد', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-natanz', 'value_1' => 'نطنز', 'parent_key' => 'province-esfhan'],
            ['key' => 'city-eshthard', 'value_1' => 'اشتهارد', 'parent_key' => 'province-alborz'],
            ['key' => 'city-sajfblagh', 'value_1' => 'ساوجبلاغ', 'parent_key' => 'province-alborz'],
            ['key' => 'city-talghan', 'value_1' => 'طالقان', 'parent_key' => 'province-alborz'],
            ['key' => 'city-fardis', 'value_1' => 'فردیس', 'parent_key' => 'province-alborz'],
            ['key' => 'city-karaj', 'value_1' => 'کرج', 'parent_key' => 'province-alborz'],
            ['key' => 'city-nazarabad', 'value_1' => 'نظرآباد', 'parent_key' => 'province-alborz'],
            ['key' => 'city-abdanan', 'value_1' => 'آبدانان', 'parent_key' => 'province-illam'],
            ['key' => 'city-illam', 'value_1' => 'ایلام', 'parent_key' => 'province-illam'],
            ['key' => 'city-eyvan', 'value_1' => 'ایوان', 'parent_key' => 'province-illam'],
            ['key' => 'city-badreh', 'value_1' => 'بدره', 'parent_key' => 'province-illam'],
            ['key' => 'city-chedaval', 'value_1' => 'چرداول', 'parent_key' => 'province-illam'],
            ['key' => 'city-darehshahr', 'value_1' => 'دره‌شهر', 'parent_key' => 'province-illam'],
            ['key' => 'city-dehloran', 'value_1' => 'دهلران', 'parent_key' => 'province-illam'],
            ['key' => 'city-sirvan', 'value_1' => 'سیروان', 'parent_key' => 'province-illam'],
            ['key' => 'city-melkshahi', 'value_1' => 'ملکشاهی', 'parent_key' => 'province-illam'],
            ['key' => 'city-mehran', 'value_1' => 'مهران', 'parent_key' => 'province-illam'],
            ['key' => 'city-booshehr', 'value_1' => 'بوشهر', 'parent_key' => 'province-booshehr'],
            ['key' => 'city-tangestan', 'value_1' => 'تنگستان', 'parent_key' => 'province-booshehr'],
            ['key' => 'city-jam', 'value_1' => 'جم', 'parent_key' => 'province-booshehr'],
            ['key' => 'city-dashtestan', 'value_1' => 'دشتستان', 'parent_key' => 'province-booshehr'],
            ['key' => 'city-dashti', 'value_1' => 'دشتی', 'parent_key' => 'province-booshehr'],
            ['key' => 'city-dir', 'value_1' => 'دیر', 'parent_key' => 'province-booshehr'],
            ['key' => 'city-deylam', 'value_1' => 'دیلم', 'parent_key' => 'province-booshehr'],
            ['key' => 'city-asalooieh', 'value_1' => 'عسلویه', 'parent_key' => 'province-booshehr'],
            ['key' => 'city-kangan', 'value_1' => 'کنگان', 'parent_key' => 'province-booshehr'],
            ['key' => 'city-gonaveh', 'value_1' => 'گناوه', 'parent_key' => 'province-booshehr'],
            ['key' => 'city-eslamshahr', 'value_1' => 'اسلامشهر', 'parent_key' => 'province-tehran'],
            ['key' => 'city-baharestan', 'value_1' => 'بهارستان', 'parent_key' => 'province-tehran'],
            ['key' => 'city-pakdasht', 'value_1' => 'پاکدشت', 'parent_key' => 'province-tehran'],
            ['key' => 'city-pardis', 'value_1' => 'پردیس', 'parent_key' => 'province-tehran'],
            ['key' => 'city-pishva', 'value_1' => 'پیشوا', 'parent_key' => 'province-tehran'],
            ['key' => 'city-tehran', 'value_1' => 'تهران', 'parent_key' => 'province-tehran'],
            ['key' => 'city-damavand', 'value_1' => 'دماوند', 'parent_key' => 'province-tehran'],
            ['key' => 'city-robatkarim', 'value_1' => 'رباط‌کریم', 'parent_key' => 'province-tehran'],
            ['key' => 'city-rey', 'value_1' => 'ری', 'parent_key' => 'province-tehran'],
            ['key' => 'city-shamiranat', 'value_1' => 'شمیرانات', 'parent_key' => 'province-tehran'],
            ['key' => 'city-shahriyar', 'value_1' => 'شهریار', 'parent_key' => 'province-tehran'],
            ['key' => 'city-firoozkooh', 'value_1' => 'فیروزکوه', 'parent_key' => 'province-tehran'],
            ['key' => 'city-ghods', 'value_1' => 'قدس', 'parent_key' => 'province-tehran'],
            ['key' => 'city-gharchak', 'value_1' => 'قرچک', 'parent_key' => 'province-tehran'],
            ['key' => 'city-molard', 'value_1' => 'ملارد', 'parent_key' => 'province-tehran'],
            ['key' => 'city-varamin', 'value_1' => 'ورامین', 'parent_key' => 'province-tehran'],
            ['key' => 'city-ardel', 'value_1' => 'اردل', 'parent_key' => 'province-charmahal-bakhtiary'],
            ['key' => 'city-brojen', 'value_1' => 'بروجن', 'parent_key' => 'province-charmahal-bakhtiary'],
            ['key' => 'city-ben', 'value_1' => 'بن', 'parent_key' => 'province-charmahal-bakhtiary'],
            ['key' => 'city-saman', 'value_1' => 'سامان', 'parent_key' => 'province-charmahal-bakhtiary'],
            ['key' => 'city-shahrekord', 'value_1' => 'شهرکرد', 'parent_key' => 'province-charmahal-bakhtiary'],
            ['key' => 'city-gharsan', 'value_1' => 'فارسان', 'parent_key' => 'province-charmahal-bakhtiary'],
            ['key' => 'city-kohrang', 'value_1' => 'کوهرنگ', 'parent_key' => 'province-charmahal-bakhtiary'],
            ['key' => 'city-kiar', 'value_1' => 'کیار', 'parent_key' => 'province-charmahal-bakhtiary'],
            ['key' => 'city-lordegan', 'value_1' => 'لردگان', 'parent_key' => 'province-charmahal-bakhtiary'],
            ['key' => 'city-bashrooieh', 'value_1' => 'بشرویه', 'parent_key' => 'province-khorasan-jonoobi'],
            ['key' => 'city-birjand', 'value_1' => 'بیرجند', 'parent_key' => 'province-khorasan-jonoobi'],
            ['key' => 'city-khosef', 'value_1' => 'خوسف', 'parent_key' => 'province-khorasan-jonoobi'],
            ['key' => 'city-darmian', 'value_1' => 'درمیان', 'parent_key' => 'province-khorasan-jonoobi'],
            ['key' => 'city-zirkooh', 'value_1' => 'زیرکوه', 'parent_key' => 'province-khorasan-jonoobi'],
            ['key' => 'city-srayan', 'value_1' => 'سرایان', 'parent_key' => 'province-khorasan-jonoobi'],
            ['key' => 'city-sarbisheh', 'value_1' => 'سربیشه', 'parent_key' => 'province-khorasan-jonoobi'],
            ['key' => 'city-tebs', 'value_1' => 'طبس', 'parent_key' => 'province-khorasan-jonoobi'],
            ['key' => 'city-ferdos', 'value_1' => 'فردوس', 'parent_key' => 'province-khorasan-jonoobi'],
            ['key' => 'city-ghaenat', 'value_1' => 'قائنات', 'parent_key' => 'province-khorasan-jonoobi'],
            ['key' => 'city-nahbendan', 'value_1' => 'نهبندان', 'parent_key' => 'province-khorasan-jonoobi'],
            ['key' => 'city-bakherz', 'value_1' => 'باخرز', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-bejestan', 'value_1' => 'بجستان', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-bardskan', 'value_1' => 'بردسکن', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-binalood', 'value_1' => 'بینالود', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-taybad', 'value_1' => 'تایباد', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-torbatjam', 'value_1' => 'تربت جام', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-torathedarieh', 'value_1' => 'تربت حیدریه', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-joghay', 'value_1' => 'جغتای', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-join', 'value_1' => 'جوین', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-chenlaran', 'value_1' => 'چناران', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-khlilabad', 'value_1' => 'خلیل‌آباد', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-khoaf', 'value_1' => 'خواف', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-khoshab', 'value_1' => 'خوشاب	', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-dowrzen', 'value_1' => 'داورزن', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-dargez', 'value_1' => 'درگز', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-rashtekhar', 'value_1' => 'رشتخوار', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-zaveh', 'value_1' => 'زاوه', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-sabzevar', 'value_1' => 'سبزوار', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-sarkhas', 'value_1' => 'سرخس', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-salehabad', 'value_1' => 'صالح‌آباد', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-friman', 'value_1' => 'فریمان', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-firoozeh', 'value_1' => 'فیروزه', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-ghoochan', 'value_1' => 'قوچان', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-khashmer', 'value_1' => 'کاشمر', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-kalat', 'value_1' => 'کلات', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-gonabad', 'value_1' => 'گناباد', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-mashhad', 'value_1' => 'مشهد', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-mehvlat', 'value_1' => 'مه‌ولات', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-neishaboor', 'value_1' => 'نیشابور', 'parent_key' => 'province-khorasan-razavi'],
            ['key' => 'city-esferain', 'value_1' => 'اسفراین', 'parent_key' => 'province-khorasan-shomali'],
            ['key' => 'city-shirvan', 'value_1' => 'شیروان', 'parent_key' => 'province-khorasan-shomali'],
            ['key' => 'city-bonjnoord', 'value_1' => 'بجنورد', 'parent_key' => 'province-khorasan-shomali'],
            ['key' => 'city-jajrom', 'value_1' => 'جاجرم', 'parent_key' => 'province-khorasan-shomali'],
            ['key' => 'city-raz-jarkglan', 'value_1' => 'راز و جرگلان', 'parent_key' => 'province-khorasan-shomali'],
            ['key' => 'city-farooj', 'value_1' => 'فاروج', 'parent_key' => 'province-khorasan-shomali'],
            ['key' => 'city-garmeh', 'value_1' => 'گرمه', 'parent_key' => 'province-khorasan-shomali'],
            ['key' => 'city-maneh-samlghan', 'value_1' => 'مانه و سملقان', 'parent_key' => 'province-khorasan-shomali'],
            ['key' => 'city-abadan', 'value_1' => 'آبادان', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-aghajari', 'value_1' => 'آغاجاری', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-omidieh', 'value_1' => 'امیدیه', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-andika', 'value_1' => 'اندیکا', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-andimeshk', 'value_1' => 'اندیمشک', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-ahvaz', 'value_1' => 'اهواز', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-izeh', 'value_1' => 'ایذه', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-baghmelk', 'value_1' => 'باغ‌ملک', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-bavi', 'value_1' => 'باوی', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-bandarmahshahr', 'value_1' => 'بندر ماهشهر', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-bebehan', 'value_1' => 'بهبهان', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-hamidieh', 'value_1' => 'حمیدیه', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-khoramshahr', 'value_1' => 'خرمشهر', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-dezfool', 'value_1' => 'دزفول', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-dashtazadegan', 'value_1' => 'دشت آزادگان', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-ramshir', 'value_1' => 'رامشیر', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-ramehmez', 'value_1' => 'رامهرمز', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-shadegan', 'value_1' => 'شادگان', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-shoosh', 'value_1' => 'شوش', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-shooshtar', 'value_1' => 'شوشتر', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-karoon', 'value_1' => 'کارون', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-gtovand', 'value_1' => 'گتوند', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-lali', 'value_1' => 'لالی', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-masjedsoleiman', 'value_1' => 'مسجدسلیمان', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-haftkal', 'value_1' => 'هفتکل', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-handijan', 'value_1' => 'هندیجان', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-hooizeh', 'value_1' => 'هویزه', 'parent_key' => 'province-khoozestan'],
            ['key' => 'city-abhar', 'value_1' => 'ابهر', 'parent_key' => 'province-zanjan'],
            ['key' => 'city-eijrood', 'value_1' => 'ایجرود', 'parent_key' => 'province-zanjan'],
            ['key' => 'city-khobandeh', 'value_1' => 'خدابنده', 'parent_key' => 'province-zanjan'],
            ['key' => 'city-khoramdareh', 'value_1' => 'خرمدره', 'parent_key' => 'province-zanjan'],
            ['key' => 'city-zanjan', 'value_1' => 'زنجان', 'parent_key' => 'province-zanjan'],
            ['key' => 'city-zoltanieh', 'value_1' => 'سلطانیه', 'parent_key' => 'province-zanjan'],
            ['key' => 'city-tarom', 'value_1' => 'طارم', 'parent_key' => 'province-zanjan'],
            ['key' => 'city-mahneshan', 'value_1' => 'ماه‌نشان', 'parent_key' => 'province-zanjan'],
            ['key' => 'city-aradan', 'value_1' => 'آرادان', 'parent_key' => 'province-semnan'],
            ['key' => 'city-damghan', 'value_1' => 'دامغان', 'parent_key' => 'province-semnan'],
            ['key' => 'city-sorkheh', 'value_1' => 'سرخه', 'parent_key' => 'province-semnan'],
            ['key' => 'city-semnan', 'value_1' => 'سمنان', 'parent_key' => 'province-semnan'],
            ['key' => 'city-shahrood', 'value_1' => 'شاهرود', 'parent_key' => 'province-semnan'],
            ['key' => 'city-garmsar', 'value_1' => 'گرمسار', 'parent_key' => 'province-semnan'],
            ['key' => 'city-mahdishar', 'value_1' => 'مهدی‌شهر', 'parent_key' => 'province-semnan'],
            ['key' => 'city-miami', 'value_1' => 'میامی', 'parent_key' => 'province-semnan'],
            ['key' => 'city-iranshahr', 'value_1' => 'ایرانشهر', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-chabahar', 'value_1' => 'چابهار', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-khash', 'value_1' => 'خاش', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-delgan', 'value_1' => 'دلگان', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-rasak', 'value_1' => 'راسک', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-zabol', 'value_1' => 'زابل', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-zahedan', 'value_1' => 'زاهدان', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-zahak', 'value_1' => 'زهک', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-saravan', 'value_1' => 'سراوان', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-sib-sooran', 'value_1' => 'سیب و سوران', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-fnooch', 'value_1' => 'فنوج', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-ghasrghand', 'value_1' => 'قصرقند', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-kenarak', 'value_1' => 'کنارک', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-mehrestan', 'value_1' => 'مهرستان', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-mirjaveh', 'value_1' => 'میرجاوه', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-nikshahr', 'value_1' => 'نیک شهر', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-nimrooz', 'value_1' => 'نیمروز', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-hamoon', 'value_1' => 'هامون', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-hirmand', 'value_1' => 'هیرمند', 'parent_key' => 'province-systan-baloochestan'],
            ['key' => 'city-abadeh', 'value_1' => 'آباده', 'parent_key' => 'province-fars'],
            ['key' => 'city-aghlid', 'value_1' => 'اقلید', 'parent_key' => 'province-fars'],
            ['key' => 'city-ehtahban', 'value_1' => 'استهبان', 'parent_key' => 'province-fars'],
            ['key' => 'city-ersanjan', 'value_1' => 'ارسنجان', 'parent_key' => 'province-fars'],
            ['key' => 'city-bevanat', 'value_1' => 'بوانات', 'parent_key' => 'province-fars'],
            ['key' => 'city-pasargad', 'value_1' => 'پاسارگاد', 'parent_key' => 'province-fars'],
            ['key' => 'city-jahrom', 'value_1' => 'جهرم', 'parent_key' => 'province-fars'],
            ['key' => 'city-khrameh', 'value_1' => 'خرامه', 'parent_key' => 'province-fars'],
            ['key' => 'city-khorambid', 'value_1' => 'خرم‌بید', 'parent_key' => 'province-fars'],
            ['key' => 'city-khanj', 'value_1' => 'خنج', 'parent_key' => 'province-fars'],
            ['key' => 'city-darab', 'value_1' => 'داراب', 'parent_key' => 'province-fars'],
            ['key' => 'city-rostam', 'value_1' => 'رستم', 'parent_key' => 'province-fars'],
            ['key' => 'city-zrindasht', 'value_1' => 'زرین‌دشت', 'parent_key' => 'province-fars'],
            ['key' => 'city-sepidan', 'value_1' => 'سپیدان', 'parent_key' => 'province-fars'],
            ['key' => 'city-servestan', 'value_1' => 'سروستان', 'parent_key' => 'province-fars'],
            ['key' => 'city-shiraz', 'value_1' => 'شیراز', 'parent_key' => 'province-fars'],
            ['key' => 'city-fesa', 'value_1' => 'فسا', 'parent_key' => 'province-fars'],
            ['key' => 'city-farashband', 'value_1' => 'فراشبند', 'parent_key' => 'province-fars'],
            ['key' => 'city-firoozabad', 'value_1' => 'فیروزآباد', 'parent_key' => 'province-fars'],
            ['key' => 'city-ghir-karzin', 'value_1' => 'قیر و کارزین', 'parent_key' => 'province-fars'],
            ['key' => 'city-kazroon', 'value_1' => 'کازرون', 'parent_key' => 'province-fars'],
            ['key' => 'city-koar', 'value_1' => 'کوار', 'parent_key' => 'province-fars'],
            ['key' => 'city-gerash', 'value_1' => 'گراش', 'parent_key' => 'province-fars'],
            ['key' => 'city-larestan', 'value_1' => 'لارستان', 'parent_key' => 'province-fars'],
            ['key' => 'city-lamrod', 'value_1' => 'لامرد', 'parent_key' => 'province-fars'],
            ['key' => 'city-marvdasht', 'value_1' => 'مرودشت', 'parent_key' => 'province-fars'],
            ['key' => 'city-momseni', 'value_1' => 'ممسنی', 'parent_key' => 'province-fars'],
            ['key' => 'city-mehr', 'value_1' => 'مهر', 'parent_key' => 'province-fars'],
            ['key' => 'city-niriz', 'value_1' => 'نی ریز', 'parent_key' => 'province-fars'],
            ['key' => 'city-abeyek', 'value_1' => 'آبیک', 'parent_key' => 'province-qazvin'],
            ['key' => 'city-avaj', 'value_1' => 'آوج', 'parent_key' => 'province-qazvin'],
            ['key' => 'city-qaz-albordz', 'value_1' => 'البرز', 'parent_key' => 'province-qazvin'],
            ['key' => 'city-booeinzahra', 'value_1' => 'بوئین‌زهرا', 'parent_key' => 'province-qazvin'],
            ['key' => 'city-takestan', 'value_1' => 'تاکستان', 'parent_key' => 'province-qazvin'],
            ['key' => 'city-qazvin', 'value_1' => 'قزوین', 'parent_key' => 'province-qazvin'],
            ['key' => 'city-qom', 'value_1' => 'قم', 'parent_key' => 'province-qom'],
            ['key' => 'city-baneh', 'value_1' => 'بانه', 'parent_key' => 'province-kordestan'],
            ['key' => 'city-bijar', 'value_1' => 'بیجار', 'parent_key' => 'province-kordestan'],
            ['key' => 'city-dehglan', 'value_1' => 'دهگلان', 'parent_key' => 'province-kordestan'],
            ['key' => 'city-divandareh', 'value_1' => 'دیواندره', 'parent_key' => 'province-kordestan'],
            ['key' => 'city-sarvabad', 'value_1' => 'سروآباد', 'parent_key' => 'province-kordestan'],
            ['key' => 'city-saghez', 'value_1' => 'سقز', 'parent_key' => 'province-kordestan'],
            ['key' => 'city-sanandaj', 'value_1' => 'سنندج', 'parent_key' => 'province-kordestan'],
            ['key' => 'city-gharveh', 'value_1' => 'قروه', 'parent_key' => 'province-kordestan'],
            ['key' => 'city-kamyaran', 'value_1' => 'کامیاران', 'parent_key' => 'province-kordestan'],
            ['key' => 'city-marivan', 'value_1' => 'مریوان', 'parent_key' => 'province-kordestan'],
            ['key' => 'city-arezooeih', 'value_1' => 'ارزوئیه', 'parent_key' => 'province-kerman'],
            ['key' => 'city-anar', 'value_1' => 'انار', 'parent_key' => 'province-kerman'],
            ['key' => 'city-baft', 'value_1' => 'بافت', 'parent_key' => 'province-kerman'],
            ['key' => 'city-bardsir', 'value_1' => 'بردسیر', 'parent_key' => 'province-kerman'],
            ['key' => 'city-bam', 'value_1' => 'بم', 'parent_key' => 'province-kerman'],
            ['key' => 'city-jiraft', 'value_1' => 'جیرفت', 'parent_key' => 'province-kerman'],
            ['key' => 'city-rabar', 'value_1' => 'رابر', 'parent_key' => 'province-kerman'],
            ['key' => 'city-ravar', 'value_1' => 'راور', 'parent_key' => 'province-kerman'],
            ['key' => 'city-rafsanjan', 'value_1' => 'رفسنجان', 'parent_key' => 'province-kerman'],
            ['key' => 'city-roodbar-jonoob', 'value_1' => 'رودبار جنوب', 'parent_key' => 'province-kerman'],
            ['key' => 'city-rigan', 'value_1' => 'ریگان', 'parent_key' => 'province-kerman'],
            ['key' => 'city-zarand', 'value_1' => 'زرند', 'parent_key' => 'province-kerman'],
            ['key' => 'city-sirjan', 'value_1' => 'سیرجان', 'parent_key' => 'province-kerman'],
            ['key' => 'city-shahbabak', 'value_1' => 'شهربابک', 'parent_key' => 'province-kerman'],
            ['key' => 'city-anbarabad', 'value_1' => 'عنبرآباد', 'parent_key' => 'province-kerman'],
            ['key' => 'city-faryab', 'value_1' => 'فاریاب', 'parent_key' => 'province-kerman'],
            ['key' => 'city-fahraj', 'value_1' => 'فهرج', 'parent_key' => 'province-kerman'],
            ['key' => 'city-ghalehganj', 'value_1' => 'قلعه گنج', 'parent_key' => 'province-kerman'],
            ['key' => 'city-kerman', 'value_1' => 'کرمان', 'parent_key' => 'province-kerman'],
            ['key' => 'city-hoohbenan', 'value_1' => 'کوهبنان', 'parent_key' => 'province-kerman'],
            ['key' => 'city-kahnooj', 'value_1' => 'کهنوج', 'parent_key' => 'province-kerman'],
            ['key' => 'city-menujan', 'value_1' => 'منوجان', 'parent_key' => 'province-kerman'],
            ['key' => 'city-narmashir', 'value_1' => 'نرماشیر', 'parent_key' => 'province-kerman'],
            ['key' => 'city-eslamabad-gharb', 'value_1' => 'اسلام‌آباد غرب', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-paveh', 'value_1' => 'پاوه', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-salasbabajani', 'value_1' => 'ثلاث باباجانی', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-javanrood', 'value_1' => 'جوانرود', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-dalahoo', 'value_1' => 'دالاهو', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-rvansar', 'value_1' => 'روانسر', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-sarpolzahab', 'value_1' => 'سرپل ذهاب', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-sangher', 'value_1' => 'سنقر', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-sahneh', 'value_1' => 'صحنه', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-ghasrshirin', 'value_1' => 'قصرشیرین', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-kermanshah', 'value_1' => 'کرمانشاه', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-kangaver', 'value_1' => 'کنگاور', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-gilangharb', 'value_1' => 'گیلانغرب', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-harsin', 'value_1' => 'هرسین', 'parent_key' => 'province-kermanshah'],
            ['key' => 'city-basht', 'value_1' => 'باشت', 'parent_key' => 'province-kohgiloovie-boierahmad'],
            ['key' => 'city-booyerahmad', 'value_1' => 'بویراحمد', 'parent_key' => 'province-kohgiloovie-boierahmad'],
            ['key' => 'city-bahmaeni', 'value_1' => 'بهمئی', 'parent_key' => 'province-kohgiloovie-boierahmad'],
            ['key' => 'city-dena', 'value_1' => 'دنا', 'parent_key' => 'province-kohgiloovie-boierahmad'],
            ['key' => 'city-charam', 'value_1' => 'چرام', 'parent_key' => 'province-kohgiloovie-boierahmad'],
            ['key' => 'city-khohgilooveh', 'value_1' => 'کهگیلویه', 'parent_key' => 'province-kohgiloovie-boierahmad'],
            ['key' => 'city-gachsaran', 'value_1' => 'گچساران', 'parent_key' => 'province-kohgiloovie-boierahmad'],
            ['key' => 'city-landeh', 'value_1' => 'لنده', 'parent_key' => 'province-kohgiloovie-boierahmad'],
            ['key' => 'city-azadshahr', 'value_1' => 'آزادشهر', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-aghghla', 'value_1' => 'آق‌قلا', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-bandargaz', 'value_1' => 'بندر گز', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-tokaman', 'value_1' => 'ترکمن', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-ramian', 'value_1' => 'رامیان', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-aliabad', 'value_1' => 'علی‌آباد', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-kordkooy', 'value_1' => 'کردکوی', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-kalaleh', 'value_1' => 'کلاله', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-galikesh', 'value_1' => 'گالیکش', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-gonbadkavoos', 'value_1' => 'گنبد کاووس', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-gorgan', 'value_1' => 'گرگان', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-gamishan', 'value_1' => 'گمیشان', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-maravehtapeh', 'value_1' => 'مراوه‌تپه', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-minoodasht', 'value_1' => 'مینودشت', 'parent_key' => 'province-gholestan'],
            ['key' => 'city-astara', 'value_1' => 'آستارا', 'parent_key' => 'province-gilan'],
            ['key' => 'city-astanehashrafieh', 'value_1' => 'آستانه اشرفیه', 'parent_key' => 'province-gilan'],
            ['key' => 'city-omlesh', 'value_1' => 'املش', 'parent_key' => 'province-gilan'],
            ['key' => 'city-bandar-anzali', 'value_1' => 'بندر انزلی', 'parent_key' => 'province-gilan'],
            ['key' => 'city-talesh', 'value_1' => 'تالش', 'parent_key' => 'province-gilan'],
            ['key' => 'city-rasht', 'value_1' => 'رشت', 'parent_key' => 'province-gilan'],
            ['key' => 'city-rezvanshahr', 'value_1' => 'رضوانشهر', 'parent_key' => 'province-gilan'],
            ['key' => 'city-roodbar', 'value_1' => 'رودبار', 'parent_key' => 'province-gilan'],
            ['key' => 'city-siahkal', 'value_1' => 'سیاهکل', 'parent_key' => 'province-gilan'],
            ['key' => 'city-sheft', 'value_1' => 'شفت', 'parent_key' => 'province-gilan'],
            ['key' => 'city-soomehsara', 'value_1' => 'صومعه‌سرا', 'parent_key' => 'province-gilan'],
            ['key' => 'city-fooman', 'value_1' => 'فومن', 'parent_key' => 'province-gilan'],
            ['key' => 'city-roodsar', 'value_1' => 'رودسر', 'parent_key' => 'province-gilan'],
            ['key' => 'city-lahijan', 'value_1' => 'لاهیجان', 'parent_key' => 'province-gilan'],
            ['key' => 'city-langrood', 'value_1' => 'لنگرود', 'parent_key' => 'province-gilan'],
            ['key' => 'city-masal', 'value_1' => 'ماسال', 'parent_key' => 'province-gilan'],
            ['key' => 'city-azna', 'value_1' => 'ازنا', 'parent_key' => 'province-lorestan'],
            ['key' => 'city-eligoodarz', 'value_1' => 'الیگودرز', 'parent_key' => 'province-lorestan'],
            ['key' => 'city-broojerd', 'value_1' => 'بروجرد', 'parent_key' => 'province-lorestan'],
            ['key' => 'city-poldokhtar', 'value_1' => 'پلدختر', 'parent_key' => 'province-lorestan'],
            ['key' => 'city-khoramabad', 'value_1' => 'خرم‌آباد', 'parent_key' => 'province-lorestan'],
            ['key' => 'city-roomeshkan', 'value_1' => 'رومشکان', 'parent_key' => 'province-lorestan'],
            ['key' => 'city-doorood', 'value_1' => 'دورود', 'parent_key' => 'province-lorestan'],
            ['key' => 'city-doreh', 'value_1' => 'دوره', 'parent_key' => 'province-lorestan'],
            ['key' => 'city-dolfan', 'value_1' => 'دلفان', 'parent_key' => 'province-lorestan'],
            ['key' => 'city-selseleh', 'value_1' => 'سلسله', 'parent_key' => 'province-lorestan'],
            ['key' => 'city-koohdasht', 'value_1' => 'کوهدشت', 'parent_key' => 'province-lorestan'],
            ['key' => 'city-amol', 'value_1' => 'آمل', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-babol', 'value_1' => 'بابل', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-babolsar', 'value_1' => 'بابلسر', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-behshahr', 'value_1' => 'بهشهر', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-tonekabon', 'value_1' => 'تنکابن', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-choobiar', 'value_1' => 'جویبار', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-chaloos', 'value_1' => 'چالوس', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-ramsar', 'value_1' => 'رامسر', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-sari', 'value_1' => 'ساری', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-savadkooh', 'value_1' => 'سوادکوه', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-north-savadkooh', 'value_1' => 'سوادکوه شمالی	', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-simorgh', 'value_1' => 'سیمرغ', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-abasabad', 'value_1' => 'عباس‌آباد', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-fereydoonkenar', 'value_1' => 'فریدونکنار', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-ghaemshahr', 'value_1' => 'قائم‌شهر', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-celardasht', 'value_1' => 'کلاردشت', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-galoogah', 'value_1' => 'گلوگاه', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-mamoodabad', 'value_1' => 'محمودآباد', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-miandrood', 'value_1' => 'میاندرود', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-neka', 'value_1' => 'نکا', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-noshahr', 'value_1' => 'نوشهر', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-noor', 'value_1' => 'نور', 'parent_key' => 'province-mazandaran'],
            ['key' => 'city-ashtian', 'value_1' => 'آشتیان', 'parent_key' => 'province-markazi'],
            ['key' => 'city-arak', 'value_1' => 'اراک', 'parent_key' => 'province-markazi'],
            ['key' => 'city-tafresh', 'value_1' => 'تفرش', 'parent_key' => 'province-markazi'],
            ['key' => 'city-khandab', 'value_1' => 'خنداب', 'parent_key' => 'province-markazi'],
            ['key' => 'city-khomein', 'value_1' => 'خمین', 'parent_key' => 'province-markazi'],
            ['key' => 'city-delijan', 'value_1' => 'دلیجان', 'parent_key' => 'province-markazi'],
            ['key' => 'city-saveh', 'value_1' => 'ساوه', 'parent_key' => 'province-markazi'],
            ['key' => 'city-shazand', 'value_1' => 'شازند', 'parent_key' => 'province-markazi'],
            ['key' => 'city-zarandieh', 'value_1' => 'زرندیه', 'parent_key' => 'province-markazi'],
            ['key' => 'city-frahan', 'value_1' => 'فراهان', 'parent_key' => 'province-markazi'],
            ['key' => 'city-kamijan', 'value_1' => 'کمیجان', 'parent_key' => 'province-markazi'],
            ['key' => 'city-mahalat', 'value_1' => 'محلات', 'parent_key' => 'province-markazi'],
            ['key' => 'city-asadabad', 'value_1' => 'اسدآباد', 'parent_key' => 'province-hamedan'],
            ['key' => 'city-bahar', 'value_1' => 'بهار', 'parent_key' => 'province-hamedan'],
            ['key' => 'city-toysavkan', 'value_1' => 'تویسرکان	', 'parent_key' => 'province-hamedan'],
            ['key' => 'city-rozan', 'value_1' => 'رزن', 'parent_key' => 'province-hamedan'],
            ['key' => 'city-famanin', 'value_1' => 'فامنین', 'parent_key' => 'province-hamedan'],
            ['key' => 'city-kaboodrahang', 'value_1' => 'کبودرآهنگ', 'parent_key' => 'province-hamedan'],
            ['key' => 'city-malayer', 'value_1' => 'ملایر', 'parent_key' => 'province-hamedan'],
            ['key' => 'city-nahavand', 'value_1' => 'نهاوند', 'parent_key' => 'province-hamedan'],
            ['key' => 'city-hamedan', 'value_1' => 'همدان', 'parent_key' => 'province-hamedan'],
            ['key' => 'city-aboomosa', 'value_1' => 'ابوموسی', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-bestak', 'value_1' => 'بستک', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-beshagard', 'value_1' => 'بشاگرد', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-bandarabas', 'value_1' => 'بندرعباس', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-bandarlangeh', 'value_1' => 'بندر لنگه', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-parsian', 'value_1' => 'پارسیان', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-jasak', 'value_1' => 'جاسک', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-hajiabad', 'value_1' => 'حاجی‌آباد', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-khomeir', 'value_1' => 'خمیر', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-roodan', 'value_1' => 'رودان', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-sirik', 'value_1' => 'سیریک', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-gheshm', 'value_1' => 'قشم', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-minab', 'value_1' => 'میناب', 'parent_key' => 'province-hormozgan'],
            ['key' => 'city-abadkooh', 'value_1' => 'ابرکوه', 'parent_key' => 'province-yazd'],
            ['key' => 'city-ashkzar', 'value_1' => 'اشکذر', 'parent_key' => 'province-yazd'],
            ['key' => 'city-ordakan', 'value_1' => 'اردکان', 'parent_key' => 'province-yazd'],
            ['key' => 'city-bafgh', 'value_1' => 'بافق', 'parent_key' => 'province-yazd'],
            ['key' => 'city-bahabad', 'value_1' => 'بهاباد', 'parent_key' => 'province-yazd'],
            ['key' => 'city-taft', 'value_1' => 'تفت', 'parent_key' => 'province-yazd'],
            ['key' => 'city-khatam', 'value_1' => 'خاتم', 'parent_key' => 'province-yazd'],
            ['key' => 'city-mehriz', 'value_1' => 'مهریز', 'parent_key' => 'province-yazd'],
            ['key' => 'city-mibad', 'value_1' => 'میبد', 'parent_key' => 'province-yazd'],
            ['key' => 'city-yazd', 'value_1' => 'یزد', 'parent_key' => 'province-yazd'],
        ], 'province');
    }
}
